#!/usr/bin/expect -f

set timeout -1
set home $env(CHIMA_ROOT)
set measure "$home/measurements"

#start telegraf service
#spawn telegraf --config $measure/telegraf.conf

#start mininet
spawn make -C $home/measurements/minimal/topology
set mininet $spawn_id
puts "Starting Mininet..."
expect -i $mininet "containernet>"
puts "Mininet ready, waiting a bit..."
sleep 8

#Close mininet
puts "Closing Mininet..."
send -i $mininet -- "exit\n"
expect -i $mininet eof
